### ISSUE TITLE
component manager blocked

### ISSUE THREAD

**Issue by Drifti** [Magento2Translations/language_es_es#2]
Installing in Magento 2.1.2 by 

cd <your magento path>
composer require magento2translations/language_nl_nl:dev-master
php bin/magento cache:clean

leads in hang up of the component manager in System, Web Setup Wizard.

The same with es_es Version.

**Comment by MrGekko** [comment]
Please continue the issue here: 
https://github.com/Magento2Translations/language_es_es/issues/2
