### ISSUE TITLE
Uninstall ?

### ISSUE THREAD

**Issue by delidiscount** [Magento2Translations/language_es_es#4]
How can I uninstall the language packages, I can not get them out.

**Comment by MrGekko** [comment]
How did you install the package?

**Comment by delidiscount** [comment]
For now we are leaving the Spanish language, the have good food for themselves.

 

 

Van: Justin van Elst [mailto:notifications@github.com] 
Verzonden: donderdag 19 oktober 2017 17:04
Aan: Magento2Translations/language_es_es
CC: Fine Food Club; Author
Onderwerp: Re: [Magento2Translations/language_es_es] Uninstall ? (#4)

 

How did you install the package?
