### ISSUE TITLE
Issue upgrading from magento 2.1.9 to 2.2.0

### ISSUE THREAD

**Issue by salelsol** [Magento2Translations/language_es_es#5]
Issue upgrading from magento 2.1.9 to 2.2.0 with composer due a this issue;
- magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
    - Conclusion: don't install magento/framework 101.0.0
    - Installation request for magento2translations/language_es_es dev-master -> satisfiable by magento2translations/language_es_es[dev-master].

**Comment by MrGekko** [comment]
Should be fixed now! I recommend using the 2.2.0 branch ;) but master tracks 2.2 for now.
